Made it so that after every failed attempt at recreating bosh-lite we destroy the vagrant deployment before exiting with an error
[#121092613]

Signed-off-by: Gabriel Ramirez <gabriel.e.ramirez@gmail.com>
Signed-off-by: Forest Eckhardt <forest.eckhardt@gmail.com>

diff --git a/scripts/recreate-bosh-lite b/scripts/recreate-bosh-lite
--- a/scripts/recreate-bosh-lite
+++ b/scripts/recreate-bosh-lite
@@ -50,7 +50,16 @@ until $(curl -k --output /dev/null --silent --head --fail https://$DEPLOYMENT_NA
     sleep 10
 done
 
-bosh -u admin -p admin -t $DEPLOYMENT_NAME.cf-app.com create user admin $PASSWORD
+# Destroy deployment if we are not able to connect and update the user
+if bosh -u admin -p admin -t $DEPLOYMENT_NAME.cf-app.com create user admin $PASSWORD; then
+  echo "Depolyment working!"
+else
+  if [ "$IAAS" = "aws" ]; then
+    echo "Deployment failed deleting instance"
+    vagrant destroy -f
+    exit 1
+  fi
+fi
 
 if test -n "$(find . -maxdepth 1 -name '*.yml' -print -quit)"; then
   rm -f *.yml
