Adds device control permissions for docker

diff --git a/scripts/start-docker b/scripts/start-docker
--- a/scripts/start-docker
+++ b/scripts/start-docker
@@ -55,6 +55,41 @@ sanitize_cgroups() {
   fi
 }
 
+function permit_device_control() {
+  local devices_mount_info=$(cat /proc/self/cgroup | grep devices)
+
+  if [ -z "$devices_mount_info" ]; then
+    # cgroups not set up; must not be in a container
+    return
+  fi
+
+  local devices_subsytems=$(echo $devices_mount_info | cut -d: -f2)
+  local devices_subdir=$(echo $devices_mount_info | cut -d: -f3)
+
+  if [ "$devices_subdir" = "/" ]; then
+    # we're in the root devices cgroup; must not be in a container
+    return
+  fi
+
+  cgroup_dir=/tmp/devices-cgroup
+
+  if [ ! -e ${cgroup_dir} ]; then
+    # mount our container's devices subsystem somewhere
+    mkdir ${cgroup_dir}
+  fi
+
+  if ! mountpoint -q ${cgroup_dir}; then
+    if ! mount -t cgroup -o $devices_subsytems none ${cgroup_dir}; then
+      return 1
+    fi
+  fi
+
+  # permit our cgroup to do everything with all devices
+  # ignore failure in case something has already done this; echo appears to
+  # return EINVAL, possibly because devices this affects are already in use
+  echo a > ${cgroup_dir}${devices_subdir}/devices.allow || true
+}
+
 start_docker() {
   if docker info >/dev/null 2>&1; then
     echo 'docker is already started'
@@ -76,6 +111,7 @@ start_docker() {
   # shellcheck disable=SC2046,SC2155
   local server_args="--mtu 1200"
 
+  permit_device_control
   mkdir -p /scratch/docker
   mkdir -p /etc/docker
 
